# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'CancerNavigator' do

use_frameworks!

#pod 'Firebase', '2.2.1'
pod 'UIScrollSlidingPages', '1.4'
pod 'SwiftEventBus', :git => 'https://github.com/cesarferreira/SwiftEventBus.git'

end

target 'CancerNavigatorTests' do

end

